FROM debian:latest
# system up-to-date
RUN apt update && apt full-upgrade -y && apt install -y wget curl python3 streamlink
# install custom plugins
COPY plugins/* /usr/lib/python3/dist-packages/streamlink/plugins/
# set entrypoint
ENTRYPOINT ["streamlink"]
