# Dockerfile.lighttpd
FROM alpine:latest

RUN apk update && apk add --no-cache \
        lighttpd \
    && rm -rf /var/cache/apk/*

RUN sed -i \
        's/^#\s*include\s*\(.*mod_fastcgi_fpm.conf.*\)$/include \1/' \
        /etc/lighttpd/lighttpd.conf

EXPOSE 80

CMD ["/usr/sbin/lighttpd", "-D", "-f", "/etc/lighttpd/lighttpd.conf"]
